### ISSUE TITLE
Event when client disconnects on server

### ISSUE THREAD

**Issue by IsseW** [billyb2/bootleg_networking#2]
There should be an event when a client disconnects from a server, to handle game things, like despawning entities etc.

**Comment by IsseW** [comment]
As there are console prints on the server when client disconnects from both native and web I imagine this is pretty doable.

**Comment by billyb2** [comment]
Hello @IsseW , is fe5361aca1450ff8b851d7c933d0a1d1a5856d13 good enough for your needs? Adding a portion to detect changes on the naia half would be possible (and I stated one way it could be done in said commit), though it would be quite a bit more effort.

**Comment by billyb2** [comment]
I think for now, I'll close this.
